//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kakuro.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kakuro.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12
        ///13
        ///14 23
        ///15 24
        ///16 25 34
        ///17 26 35
        ///18 27 36 45
        ///19 28 37 46
        ///29 38 47 56
        ///39 48 57
        ///49 58 67
        ///59 68
        ///69 78
        ///79
        ///89
        ///123
        ///124
        ///125 134
        ///126 135 234
        ///127 136 145 235
        ///128 137 146 236 245
        ///129 138 147 156 237 246 345
        ///139 148 157 238 247 256 346
        ///149 158 167 239 248 257 347 356
        ///159 168 249 258 267 348 357 456
        ///169 178 259 268 349 358 367 457
        ///179 269 278 359 368 458 467
        ///189 279 369 378 459 468 567
        ///289 379 469 478 568
        ///389 479 569 578
        ///489 579 678
        ///589 679
        ///689
        ///789
        ///1234
        ///1235
        ///1236 1245
        ///1237 1246 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string combos {
            get {
                return ResourceManager.GetString("combos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23 3456789
        ///24 2456789
        ///25 56789
        ///26 36789
        ///27 789
        ///28 489
        ///29 9
        ///210 5
        ///211 1
        ///212 126
        ///213 123
        ///214 12347
        ///215 12345
        ///216 1234568
        ///217 1234567
        ///36 456789
        ///37 356789
        ///38 6789
        ///39 789
        ///310 89
        ///311 9
        ///319 1
        ///320 12
        ///321 123
        ///322 1234
        ///323 123457
        ///324 123456
        ///410 56789
        ///411 46789
        ///412 789
        ///413 89
        ///414 9
        ///426 1
        ///427 12
        ///428 123
        ///429 12346
        ///430 12345
        ///515 6789
        ///516 5789
        ///517 89
        ///518 9
        ///532 1
        ///533 12
        ///534 1235
        ///535 1234
        ///621 789
        ///622 689
        ///623 9
        ///637 1
        ///638 124
        ///639 123
        ///728 89
        ///729 79
        ///741 13
        ///742 12
        ///836 9
        ///837 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string unused {
            get {
                return ResourceManager.GetString("unused", resourceCulture);
            }
        }
    }
}
